########################################################################################
# +----------------------------------------------------------------------------------+ #
# |                 Police Extension for Essentials                                  | #
# |  Inofficial & Unaffiliated with Essentials Development Team                      | #
# |                                                                                  | #
# |  Credits for Essentials Plugin:                                                  | #
# |    "Essentials is currently developed and maintained by ementalo, snowleo, and   | #
# |     KHobbits. Many thanks to the past developers and contributors: Zenexer,      | #
# |     Aelux, Brettflan, KimKandor, ceulemans, necrodoom and Xeology.               | #
# |                                                                                  | #
# |  Please note that as an extension, this plugin requires Essentials.              | #
# |  You can find Essentials at http://dev.bukkit.org/server-mods/essentials/        | #
# |                                                                                  | #
# +----------------------------------------------------------------------------------+ #
########################################################################################

# SQL Setup
# If use is set to false, using flatfile instead
sql:
  use: 'true'
  database: test
  user: test
  password: test
  host: localhost
  port: 3306
  sql_timeout: 5

# Automatically ban after X jail sentences
# Set to 0 to disable
jail_autoban_number: 3

# Default ban reason if none is specified
default_ban_reason: 'The Ban Hammer has spoken!'

# When moderators jail, their current location is stored so they can return later to help remind them what the jail sentence was about
# The default world is skipped from the location statement to avoid clutter
# Set this to something different than any of your worlds to disable this skipping of information
default_world: 'world'